onground = false;
grav = 1;
move_speed = 4;
jump_strength = -20;
hsp = 0;
vsp = 0;
hsp_slow = 0;
vsp_slow = 0;
jump_controll = (room == room_tutorial);
prov_e = 1;
pos_history_x = ds_list_create();
pos_history_y = ds_list_create();
max_history = game_get_speed(gamespeed_fps) * 5;
rewind_cooldown = 0;